Run xcodebuild build \
Command line invocation:
    /Applications/Xcode_16.1.app/Contents/Developer/usr/bin/xcodebuild build -project ios/Jetlink.xcodeproj -scheme Jetlink -destination generic/platform=iOS -configuration Release -derivedDataPath ios/build/DerivedData CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/runner/work/jetlink/jetlink/ios/build/DerivedData
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

Resolve Package Graph
package 'jetlinkkit' is using Swift tools version 6.2.0 but the installed version is 6.0.0
2026-09-28 10:25:43.029 xcodebuild[1994:8844] Writing error result bundle to /var/folders/s6/5hzmn6lx4dz5nxs7k_0slzph0000gn/T/ResultBundle_2026-28-09_10-25-0043.xcresult

Resolved source packages:
  JetlinkKit: (null)

xcodebuild: error: Could not resolve package dependencies:
  package 'jetlinkkit' is using Swift tools version 6.2.0 but the installed version is 6.0.0

Error: Process completed with exit code 74.
